<!doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type: text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="es" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="busqueda, cap, buscar pregunta" />
    <meta name="author" content="Fco Sanz">
    <meta name="description" content="Permite la búsqueda de test en mundoCAP">
    <title>Búsqueda MundoCap</title>

    <link rel="stylesheet" href="<?php echo INIT?>/src/css/test.css">
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/foundation-icons.css">
</head>
<body>

<noscript>
    <p>Su navegador no admite javascript. Por favor activeló para la navegación.</p>
</noscript>
<a name="arriba"></a>
    <header id="foo">
        <div class="grid-x navegacion grid-padding-x">
            <div class="cell">
                <div class="top-bar">
                    <div class="top-bar-left">
                        <a href="<?php echo INIT?>/">
                            <img src="<?php echo INIT?>/src/images/globo3.png" height="62" width="62">
                        </a>
                        <h2 style="display: none;">certificado de aptitud Profesional</h2>
                    </div>
                    <div class="top-bar-right">
                        <a data-toggle="menuPrincipal" class="menu-icon" style="line-height: -10rem;"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid-x grid-padding-x">
            <div class="cell">
                <a href="<?php echo INIT?>/">Inicio</a>  >> <span style="color: #2ca02c"><?php echo $enlace?></span>
            </div>
        </div>
        <div class="grid-x">
            <div class="cell">
                <div class="callout primary text-center">
                    Se rescatarán 100 registros máximo. Si no encuentra lo que busca, pruebe una búsqueda más exacta.
                </div>
            </div>
        </div>
    </header>

    <div class="off-canvas-wrapper">
        <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
            <nav class="off-canvas position-left" id="menuPrincipal" data-off-canvas data-transition="push">
                <?php require_once 'navegacion.phtml'?>
            </nav>

            <div class="off-canvas-content" data-off-canvas-content>
                <div class="grid-x grid-padding-x" style="background-color:#d8d8d8; padding-top: 1rem;">
                <section class="grid-container">
                    <?php $contador = 1; foreach ($preguntas as $pregunta) { ?>
                        <div class="callout secondary">
                            <p><span class="primary badge" style="font-size: 15px; font-weight: bold; background-color: #2ca02c"><?php echo $contador ?></span></p>
                            <p>COD: <?php echo $pregunta->cod ?></p>

                            <p style="color: #2ca02c; font-weight: 600; font-size: 1.4rem;"><?php echo $pregunta->pregunta?></p>
                            <span <?php if (trim($pregunta->solucion)=='A') echo 'style="color: green"'?>><?php echo 'A. '.$pregunta->respA ?></span>
                            <br>
                            <span <?php if (trim($pregunta->solucion)=='B') echo 'style="color: green"'?>><?php echo 'B. '.$pregunta->respB ?></span>
                            <br>
                            <span <?php if (trim($pregunta->solucion)=='C') echo 'style="color: green"'?>><?php echo 'C. '.$pregunta->respC ?></span>
                            <br>
                            <span <?php if (trim($pregunta->solucion)=='D') echo 'style="color: green"'?>><?php echo 'D. '.$pregunta->respD ?></span>
                            <br><br>
                            <p style="color: green;"><?php echo "Solución: ".$pregunta->solucion ?></p>
                            <p><?php echo $pregunta->norma ?></p>
                        </div>
                        <?php $contador++; }?>

                        <?php if (!count($preguntas)) {?>
                            <div class="grid-x">
                                <div class="small-10 cell">
                                    <p class="text-center">
                                        No se han encontrado datos con los parámetros de búsqueda introducidos.
                                    </p>
                                </div>
                            </div>
                        <?php }?>
                        <div class="grid-x" style="margin-bottom: 1rem">
                            <div class="cell text-right">
                                <a class="primary badge" href="#arriba" style="font-size: 20px; font-weight: bold;"><span class="fi-arrow-up"></span></a>
                            </div>
                        </div>
                </section>
                </div>
            </div>
<?php require_once 'footer.phtml'?>
</div>
</div>

<?php if (empty($_SESSION['ocultarC'])) {
    require_once 'ocultar.phtml';
}?>

<script src="<?php echo INIT?>/modules/jquery/dist/jquery.js"></script>
<script src="<?php echo INIT?>/modules/what-input/dist/what-input.js"></script>
<script src="<?php echo INIT?>/modules/foundation-sites/dist/js/foundation.js"></script>
<script src="<?php echo INIT?>/src/js/app2.js"></script>

<?php if (MODO=='production'){ ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50863084-1', 'mundocap.es');
        ga('send', 'pageview');

    </script>
<?php } ?>
</body>
