<!doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="cookies mundocap, cookies" />
    <meta name="author" content="Fco Sanz">
    <meta name="description" content="Infomación de cookies y disposiciones legales en mundoCAP">
    <title>Cookies MundoCap</title>
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/test.css">
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/foundation-icons.css">
</head>
<body>
<noscript>
    <p>Su navegador no admite javascript. Por favor activeló para la navegación.</p>
</noscript>
<header id="foo">
    <div class="grid-x navegacion grid-padding-x">
        <div class="cell">
            <div class="top-bar">
                <div class="top-bar-left">
                    <a href="<?php echo INIT?>/">
                        <img src="<?php echo INIT?>/src/images/globo3.png" height="62" width="62">
                    </a>
                    <h2 style="display: none;">certificado de aptitud Profesional</h2>
                </div>
                <div class="top-bar-right">
                    <a data-toggle="menuPrincipal" class="menu-icon" style="line-height: -10rem;"></a>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-x grid-padding-x" style="background-color: #d8d8d8">
        <div class="cell">
            <a href="<?php echo INIT?>/">Inicio</a> >> Cookies-uso-condiciones
        </div>
    </div>
</header>
<br>
<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
        <nav class="off-canvas position-left" id="menuPrincipal" data-off-canvas data-transition="push">
            <?php require_once 'navegacion.phtml'?>
        </nav>

        <div class="off-canvas-content" data-off-canvas-content>
            <div class="grid-x grid-padding-x grid-margin-x">
                <div class="cell medium-4"></div>
                <div class="cell medium-8"><h1>Política de Cookies, uso y Legalidad</h1>
                    <hr></div>
            </div>

            <div class="grid-x grid-padding-x grid-margin-x">

                <div class="cell medium-4">
                    <div class="stiky">
                        <ol>
                            <li><a href="#informacion" id="informacion">¿ Qué son las Cookies ?</a></li>
                            <li><a href="#tipo" id="tipo">¿ Qué tipo de <i>cookies</i> existen ?</a></li>
                            <li><a href="#uso" id="uso">¿ Qué tipo de <i>cookies</i> usamos ?</a></li>
                            <li><a href="#eliminar" id="eliminar">¿ Cómo bloquear o eliminar las <i>cookies</i> instaladas en su equipo ?</a></li>
                            <li><a href="#usuarios" id="usuarios">Datos de usuarios</a></li>
                            <li><a href="#privacidad" id="privacidad">Privacidad</a></li>
                            <li><a href="#responsabilidades" id="responsabilidad">Exclusión responsabilidad</a></li>
                        </ol>
                    </div>
                </div>
                <div class="cell medium-8">
                    <h3 class="informacion"><a>1. ¿ Qué son las <i>Cookies</i> ?</a></h3>
                    <p>Una <i>cookies</i> es un pequeño fragmento de texto que los sitios web
                        que visitas envían al navegador y que permite que el sitio web
                        recuerde información sobre tu visita, como tu idioma preferido y otras opciones,
                        lo que puede facilitar tu próxima visita y hacer que el sitio te resulte más útil.
                        Las cookies desempeñan un papel muy importante, ya que sin ellas el uso de la Web
                        sería una experiencia mucho más frustrante.</p>
                    <p>A través de las <i>cookies</i>, los prestadores de servicios obtienen datos
                        relacionados con los usuarios que posteriormente podrán ser utilizados
                        para la prestación de los servicios concretos, para servir publicidad o
                        como base para el desarrollo de mejoras o nuevos productos y servicios en ocasiones gratuitos.</p>
                    <p>Más información en <a href="https://es.wikipedia.org/wiki/Cookie_(inform%C3%A1tica)">https://es.wikipedia.org/wiki/Cookie_(inform%C3%A1tica)</a></p>

                    <h3 class="tipo"><a name="tipo">2. ¿ Qué tipo de cookies existen ?</a></h3>
                    <p>
                        <strong>A.
                        Según quien sea la entidad que gestione el equipo o dominio desde donde se envían las cookies y trate los datos que se obtengan,
                        podemos distinguir:</strong>
                    </p>
                    <ul>
                        <li>
                            <strong><i>Cookies</i> propias :</strong>
                            Son aquéllas que se envían al equipo terminal del usuario desde un equipo o dominio gestionado por el propio editor y desde el que se presta el
                            servicio solicitado por el usuario.
                        </li>
                        <li>
                            <strong><i>Cookies</i> de Terceros:</strong>
                            Son aquéllas que se envían al equipo terminal del usuario desde un equipo o dominio que no es gestionado por el editor, sino por otra entidad
                            que trata los datos obtenidos través de las cookies.<br>
                            En el caso de que las <i>Cookies</i> sean instaladas desde un equipo o dominio gestionado por el propio editor pero la información que se recoja
                            mediante éstas sea gestionada por un tercero, no pueden ser consideradas como cookies propias.
                        </li>
                    </ul>
                    <p>
                        <strong>B.
                        Tipos de cookies según el plazo de tiempo que permanecen en el equipo Terminal podemos distinguir:
                        </strong>
                    </p>
                    <ul>
                        <li>
                            <strong><i>Cookies</i> de sesión</strong>
                            Son un tipo de <i>Cookies</i> diseñadas para recabar y almacenar datos mientras el usuario accede a una página web.<br>
                            Se suelen emplear para almacenar información que solo interesa conservar para la prestación del servicio solicitado por el usuario en una
                            sola ocasión (p.e. una lista de productos adquiridos).
                        </li>
                        <li>
                            <strong>Cookies persistentes</strong>
                            Son un tipo de <i>Cookies</i> en el que los datos siguen almacenados en el terminal y pueden ser accedidos y tratados durante un periodo definido
                            por el responsable de la cookie, y que puede ir de unos minutos a varios años.
                        </li>
                    </ul>
                    <p>
                        <strong>C.
                        Tipos de <i>Cookies</i> según su finalidad:
                        </strong>
                    </p>
                    <ul>
                        <li>
                            <strong><i>Cookies</i> técnicas</strong>
                            Son aquéllas que permiten al usuario la navegación a través de una página web, plataforma o aplicación y la utilización de las diferentes
                            opciones o servicios que en ella existan; como, por ejemplo, controlar el tráfico y la comunicación de datos, identificar la sesión,
                            acceder a partes de acceso restringido, recordar los elementos que integran un pedido, realizar el proceso de compra de un pedido,
                            realizar la solicitud de inscripción o participación en un evento, utilizar elementos de seguridad durante la navegación, almacenar
                            contenidos para la difusión de videos o sonido o compartir contenidos a través de redes sociales.
                        </li>
                        <li>
                            <strong><i>Cookies</i> de personalización</strong>
                            Son aquéllas que permiten al usuario acceder al servicio con algunas características de carácter general predefinidas en función de una
                            serie de criterios en el terminal del usuario como por ejemplo serian el idioma, el tipo de navegador a través del cual accede al servicio,
                            la configuración regional desde donde accede al servicio, etc.
                        </li>
                        <li>
                            <strong><i>Cookies</i> de análisis</strong>
                            Son aquéllas que permiten al responsable de las mismas, el seguimiento y análisis del comportamiento de los usuarios de los sitios Web a
                            los que están vinculadas.<br
                            La información recogida mediante este tipo de <i>Cookies</i> se utiliza en la medición de la actividad de los sitios web, aplicación o plataforma
                            y para la elaboración
                            de perfiles de navegación de los usuarios de dichos sitios, aplicaciones y plataformas, con el fin de introducir mejoras en función del
                            análisis de los datos de uso que hacen los usuarios del servicio.
                        </li>
                        <li>
                            <strong><i>Cookies</i> publicitarias</strong>
                            Son aquéllas que permiten la gestión, de la forma más eficaz posible, de los espacios publicitarios que, en su caso, el editor haya incluido
                            en una página web, aplicación o plataforma desde la que presta el servicio solicitado en base a criterios como el contenido editado o la
                            frecuencia en la que se muestran los anuncios.
                        </li>
                        <li>
                            <strong><i>Cookies</i> de publicidad comportamental</strong>
                            Son aquéllas que permiten la gestión, de la forma más eficaz posible, de los espacios publicitarios que, en su caso, el editor haya incluido
                            en una página Web, aplicación o plataforma desde la que presta el servicio solicitado.<br
                            Estas <i>Cookies</i> almacenan información del comportamiento de los usuarios obtenida a través de la observación continuada de sus hábitos de navegación,
                            lo que permite desarrollar un perfil específico para mostrar publicidad en función del mismo.
                        </li>
                    </ul>

                    <h3 class="uso"><a>3. ¿ Qué tipo de <i>cookies</i> usamos ?</a></h3>
                    <p>Usamos cookies de sesión, no permanentes, para el uso correcto de la Web<br>
                        Asimismo usamos <i>cookies</i> de terceros de Google, con el fin de tener un estudio estadístico de las visitas a la Web por parte de los usuarios.
                        Estas <i>cookies</i> de Google no identifica personalmente a ningún usuario.
                        Esto es una práctica habitúal en las WebSites.
                        Si le interesa saber más sobre como gestiona Google esta información puede dirigirse al siguiente enlace: <a href="https://www.google.es/intl/es/policies/technologies/cookies/">https://www.google.es/intl/es/policies/technologies/cookies/</a>
                    </p>
                    <p>Si usted no está de acuerdo con nuestra política de <i>cookies</i> <b>puede desactivarlas</b>;
                        pero tenga en cuenta, que en ese caso, dejará de serle útil esta Web e impedirá la utilización correcta de ella.
                    </p>

                    <h3 class="eliminar"><a>4. ¿ Cómo bloquear o eliminar las cookies instaladas en su equipo ?</a></h3>
                    <p>Depende del navegador podrá usted eliminar o bloquear las <i>cookies</i>:</p>
                    <ul>
                        <li>Firefox: <br> <a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we">
                                https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we</a>
                        </li>
                        <li>Internet Explorer: <br><a href="https://support.microsoft.com/es-es/help/17442/windows-internet-explorer-delete-manage-cookies">https://support.microsoft.com/es-es/help/17442/windows-internet-explorer-delete-manage-cookies</a>
                        </li>
                        <li>Microsoft Edge: <br><a href="https://privacy.microsoft.com/es-ES/windows-10-microsoft-edge-and-privacy">https://privacy.microsoft.com/es-ES/windows-10-microsoft-edge-and-privacy</a></li>
                        <li>Google Chrome: <br><a href="https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=es">https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=es</a></li>
                        <li>Safari en Ipad, Iphone: <br><a href="https://support.apple.com/es-es/HT201265">https://support.apple.com/es-es/HT201265</a></li>
                        <li>Opera: <br><a href="http://help.opera.com/Windows/11.50/es-ES/cookies.html">http://help.opera.com/Windows/11.50/es-ES/cookies.html</a></li>
                    </ul>
                    <p>Para cualquier otro navegador puede hacer una búsqueda en la Web de manera fácil.</p>

                    <h3 class="usuarios"><a>5. Datos de usuarios</a></h3>
                    <p>El único dato que mundoCap recopila y de manera voluntaria es el e-mail y su respectiva contraseña codificada, para poder dar
                        el servicio adecuado.</p>
                    <p>Los usuarios que se hayan dado de alta, según lo previsto en la Ley Orgánica de protección de datos,
                        podrán ejercer su derecho a darse de baja y a la rectificación.</p>
                    <p>Para darse de baja hay una opción en la parte de la navegación o a pie de página.
                    Respecto a la rectificación se podrá hacer enviando un e-mail al administrador, opción también disponible.</p>

                    <h3 class="privacidad"><a>6. Privacidad</a></h3>
                    <p>Lo único que se guarda en una base de datos es el e-mail y contraseña. En ningún momento identificamos a personas físicas.</p>

                    <h3 class="responsabilidad"><a>7. Exclusión de responsabilidad</a></h3>
                    <p>Aunque los datos que facilitamos y mostramos estan recogidos de la página oficial de Fomento y de forma automátizada (En el caso del CAP)
                    , y de la Dirección General de Tráfico para el ADR, mundoCap no se hace responsable de la exactitud,
                        fiabilidad o actualidad de los datos mostrados; aún, cuando se pone especial énfasis en que los datos mostrados sean los originales ofrecidos por dichas entidades.</p>
                    <p>Para seguir navegando por esta Web, el usuario tiene que estar de acuerdo con esta política de mundoCap.</p>
                </div>
            </div>
            <br>
            <?php require_once 'footer.phtml'?>
        </div>
    </div>
</div>

<?php if (empty($_SESSION['ocultarC'])) {
    require_once 'ocultar.phtml';
}?>
<script src="<?php echo INIT?>/modules/jquery/dist/jquery.js"></script>
<script src="<?php echo INIT?>/modules/what-input/dist/what-input.js"></script>
<script src="<?php echo INIT?>/modules/foundation-sites/dist/js/foundation.js"></script>
<script src="<?php echo INIT?>/src/js/appCookies.js"></script>

<?php if (MODO=='production'){ ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50863084-1', 'mundocap.es');
        ga('send', 'pageview');

    </script>
<?php } ?>
</body>
</html>