<footer>
    <div class="grid-x">
        <div class="medium-8 cell">
            <ul class="menu vertical large-horizontal">
                <li><a href="<?php echo INIT?>/cap/login">Inicio Sesión</a></li>
                <li><a href="<?php echo INIT?>/cap/alta">Date de Alta</a></li>
                <li><a href="<?php echo INIT?>/cap/logout">Cierre Sesión</a></li>
                <li><a href="<?php echo INIT?>/cap/cookies">Cookies/Uso/Condiciones</a></li>
            </ul>
            <p>
                &nbsp;&nbsp;<a aria-label="compartir en Facebook" href="https://www.facebook.com/sharer/sharer.php?u=www.mundocap.es"><i class="fi-social-facebook" style="font-size: 1.4em;"></i> Compartir en Facebook</a>
                &nbsp;&nbsp;
                &nbsp;&nbsp;<a aria-label="compartir en Twitter" href="https://twitter.com/home?status=www.mundocap.es"><i class="fi-social-twitter" style="font-size: 1.4em;"></i>Compartir en Twitter</a>
            </p>

        </div>

        <div class="medium-4 cell">
            <p class="ap">Última actulización a <?php echo VERSION?></p>
            <p class="contacta"><a href="<?php echo INIT?>/cap/email">Contacta Conmigo</a></p>
        </div>
    </div>
    <div class="grid-x pie">
        <div class="cell text-center">
            <p>Copyright 2018</p>
        </div>
    </div>
</footer>