<!doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords"
          content="cap mercancias, cap viajeros, test cap mercancias, test cap viajeros, test cap, mundocap, cap, examenes cap, examenes mercancia, examenes viajeros, test viajeros, test mercancias"/>
    <meta name="author" content="Fco Sanz">
    <meta name="description"
          content="Aprende y supera el CAP. Método único y seguro basado en test del CAP de Mercancias y Viajeros con características avanzadas, simulacros y test reales.">
    <title>MundoCap</title>
    <link rel="stylesheet" href="<?php echo INIT ?>/src/css/app.css">
    <link rel="stylesheet" href="<?php echo INIT ?>/src/css/foundation-icons.css">
</head>
<body>
<noscript>
    <p>Su navegador no admite javascript. Por favor activeló para la navegación.</p>
</noscript>
<!--
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v3.2';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
-->
<p style="position: absolute; top: 1rem; left: 1rem; z-index: 1;">
    <?php
    if (!empty($_SESSION['usuario'])) {
        echo 'Usted tiene acceso. <br> <a href="' . INIT . '/cap/logout">Cerrar Sesión</a>';
    } else {
        echo '<a href="' . INIT . '/cap/login">Identifícate por favor</a>';
    }
    ?>
    &nbsp;
    <a class="hide-for-small-only" style="font-size: 2rem; position: relative; top: 5px;"
       aria-label="compartir en Facebook" href="https://www.facebook.com/sharer/sharer.php?u=www.mundocap.es"><i
                class="fi-social-facebook"></i></a>
    &nbsp;
    <a class="hide-for-small-only" style="font-size: 2rem; position: relative; top: 5px;"
       aria-label="compartir en Twitter" href="https://twitter.com/home?status=www.mundocap.es"><i
                class="fi-social-twitter"></i></a>
</p>
<nav class="navegacion">
    <a data-toggle="menuPrincipal" class="menu-icon"></a>
</nav>

<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>

        <div class="off-canvas position-left" id="menuPrincipal" data-off-canvas data-transition="push">
            <?php require_once 'navegacion.phtml' ?>
        </div>

        <div class="off-canvas-content" data-off-canvas-content>
            <header>
                <div class="imagen"></div>
                <div class="encabezado">
                    <div class="grid-x relleno">
                        <div class="cell">
                            <h1 class="h1 text-center">LA MANERA MÁS FÁCIL DE SUPERAR EL <abbr
                                        title="Certificado de Aptitud Profesional">CAP</abbr></h1>
                        </div>
                    </div>
                </div>
            </header>

            <div class="grid-x text-center expli">
                <div class="medium-12 cell">
                    <h2 class="menu menu-text align-center h3" style="font-weight: bold">MEJORES TEST DE MERCANCIAS Y DE
                        VIAJEROS</h2>
                    <!--
                    <ul class="menu simple align-center">
                        <li class="menu-text">LOS MEJORES TEST DE MERCANCIAS Y DE VIAJEROS</li>
                    </ul>
                    -->
                </div>
            </div>

            <div id="parallax-1">
                <div class="grid-container">
                    <div class="grid-x text-center nuevo">
                        <div class="medium-6 large-4 cell">
                            <i class="fi-mobile"> </i><i class="fi-laptop"> </i><i class="fi-monitor"></i>
                            <p><strong>Multidispositivo</strong></p>
                            <ul class="no-bullet">
                                <li>Disponible en todos los dispositivos</li>
                                <li>Úsalo en cualquier momento y lugar</li>
                            </ul>
                        </div>
                        <div class="medium-6 large-4 cell">
                            <i class="fi-target-two"></i>
                            <p><strong>Test Oficiales</strong></p>
                            <ul class="no-bullet">
                                <li>Simulacros Reales de Fomento</li>
                                <li>Simulacros similar al examen</li>
                                <li>Filtra por palabras claves</li>
                            </ul>
                        </div>
                        <div class="medium-6 large-4 cell">
                            <i class="fi-lock"></i>
                            <p><strong>Seguro</strong></p>
                            <ul class="no-bullet">
                                <li>Preguntas oficiales de <a style="border-bottom: blue dotted 1px"
                                                              href="https://www.fomento.gob.es/">Fomento</a></li>
                                <li>Algoritmo mucho más eficiente</li>
                                <li>Totalmente Actualizado</li>
                            </ul>
                        </div>
                        <div class="medium-6 large-4 cell">
                            <i class="fi-checkbox"></i>
                            <p><strong>Test personalizados</strong></p>
                            <ul class="no-bullet">
                                <li>Mercancía, Viajeros y Comunes</li>
                                <li>Test no repetibles</li>
                            </ul>
                        </div>
                        <div class="medium-6 large-4 cell">
                            <i class="fi-graph-bar"></i>
                            <p><strong>Estadísticas</strong></p>
                            <ul class="no-bullet">
                                <li>Seguimientos de tus avances</li>
                                <li>Repaso preguntas erróneas</li>
                            </ul>
                        </div>
                        <div class="medium-6 large-4 cell">
                            <i class="fi-widget"></i>
                            <p><strong>Práctico</strong></p>
                            <ul class="no-bullet">
                                <li>Rápido, Sin publicidad ni Spam</li>
                                <li>Algoritmo eficiente</li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="grid-x grid-margin-x grid-padding-x todo2">
                <div class="medium-6 cell radius">
                    <h2 class="h4 tarjeta text-center">TEST MERCANCÍAS</h2>
                    <div class="callout primary llamada">
                        <ol>
                            <li><a data-open="mercancia-todas">Mercancías (1877 Preg.)</a></li>
                            <div class="reveal" data-reveal id="mercancia-todas" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Mercancías</p>
                                <p class="h5">General</p>
                                <div class="callout success">
                                    <form id="fmt" action="<?php echo INIT ?>/cap/test/mercancia/todas">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasMT" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginMercanciaMT" class="button"
                                               value="Comenzar Examen">
                                        <p style="color: red" class="help-text MT"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="mercancia-conduccion">Conducción Racional (450 Preg.)</a></li>
                            <div class="reveal" data-reveal id="mercancia-conduccion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Mercancías</p>
                                <p class="h5">Conducción Racional</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/mercancia/conduccion-racional">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasMC" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginMercanciaMC" class="button"
                                               value="Comenzar Examen">
                                        <p style="color: red" class="help-text MC"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="mercancia-aplicacion">Aplicación Reglamentación (842 Preg.)</a></li>
                            <div class="reveal" data-reveal id="mercancia-aplicacion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Mercancías</p>
                                <p class="h5">Aplicación del Reglamento</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/mercancia/aplicacion-reglamento">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasMA" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginMercanciaMA" class="button"
                                               value="Comenzar Examen">
                                        <p style="color: red" class="help-text MA"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="mercancia-salud">Salud, Seguridad Vial, Serv. y Logística (585 Preg.)</a>
                            </li>
                            <div class="reveal" data-reveal id="mercancia-salud" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Mercancías</p>
                                <p class="h5">Salud, Seguridad y Logística</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/mercancia/salud-seguridad-logistica">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasMS" name="preguntas" pattern="\[0-9]{1}"
                                                   required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginMercanciaMS" class="button"
                                               value="Comenzar Examen">
                                        <p style="color: red" class="help-text MS"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                        </ol>
                    </div>
                </div>
                <div class="medium-6 cell radius">
                    <h2 class="h4 tarjeta text-center">TEST VIAJEROS</h2>
                    <div class="callout primary llamada">
                        <ol>
                            <li><a data-open="viajero-todas">Viajeros (1228 Preg.)</a></li>
                            <div class="reveal" data-reveal id="viajero-todas" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Viajeros</p>
                                <p class="h5">General</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/viajero/todas">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasVT" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginViajeroVT" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text VT"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="viajero-conduccion">Conducción Racional (372 Preg.)</a></li>
                            <div class="reveal" data-reveal id="viajero-conduccion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Viajeros</p>
                                <p class="h5">Conducción Racional</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/viajero/conduccion-racional">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasVC" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginViajeroVC" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text VC"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="viajero-aplicacion">Aplicación Reglamentación (497 Preg.)</a></li>
                            <div class="reveal" data-reveal id="viajero-aplicacion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Viajeros</p>
                                <p class="h5">Aplicación del Reglamento</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/viajero/aplicacion-reglamento">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasVA" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginViajeroVA" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text VA"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="viajero-salud">Salud, Seguridad Vial, Serv. y Logística (359 Preg.)</a>
                            </li>
                            <div class="reveal" data-reveal id="viajero-salud" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Viajeros</p>
                                <p class="h5">Salud, Seguridad y Logística</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/viajero/salud-seguridad-logistica">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasVS" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginViajeroVS" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text VS"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                        </ol>
                    </div>
                </div>
            </div>
            <div class="grid-x grid-margin-x grid-padding-x todo3">
                <div class="medium-6 cell radius">
                    <h2 class="h4 tarjeta text-center">TEST COMUNES</h2>
                    <div class="callout primary llamada">
                        <ol>
                            <li><a data-open="comunes-todas">Comunes (5041 Preg.)</a></li>
                            <div class="reveal" data-reveal id="comunes-todas" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Comunes</p>
                                <p class="h5">General</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/comunes/todas">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasCT" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginComunesCT" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text CT"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="comunes-conduccion">Conducción Racional (2397 Preg.)</a></li>
                            <div class="reveal" data-reveal id="comunes-conduccion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Comunes</p>
                                <p class="h5">Conducción Racional</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/comunes/conduccion-racional">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasCC" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginComunesCC" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text CC"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="comunes-aplicacion">Aplicación Reglamentación (700 Preg.)</a></li>
                            <div class="reveal" data-reveal id="comunes-aplicacion" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Comunes</p>
                                <p class="h5">Aplicación del Reglamento</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/comunes/aplicacion-reglamento">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasCA" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginComunesCA" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text CA"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="comunes-salud">Salud, Seguridad Vial, Serv. y Logística (1943 Preg.)</a>
                            </li>
                            <div class="reveal" data-reveal id="comunes-salud" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test de Comunes</p>
                                <p class="h5">Salud, Seguridad y Logística</p>
                                <div class="callout success">
                                    <form action="/<?php echo INIT ?>cap/test/comunes/salud-seguridad-logistica">
                                        <label>Número Preguntas
                                            <input type="text" class="preguntasCS" name="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginComunesCS" class="button" value="Comenzar Examen">
                                        <p style="color: red" class="help-text CS"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                        </ol>
                    </div>
                </div>
                <div class="medium-6 cell radius">
                    <h2 class="h4 tarjeta text-center">SIMULACROS DE EXAMÉN</h2>
                    <div class="callout primary llamada">
                        <ol>
                            <li><a href="<?php echo INIT ?>/cap/test/simulacro/mercancia">Simulacro Mercancía</a></li>
                            <li><a href="<?php echo INIT ?>/cap/test/simulacro/viajero">Simulacro Viajeros</a></li>
                            <li class="no-visible">&nbsp;</li>
                            <li class="no-visible">&nbsp;</li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="grid-x grid-margin-x grid-padding-x todo4">
                <div class="medium-6 medium-centered cell radius">
                    <h2 class="h4 tarjeta text-center">ÉXITO ASEGURADO
                        <small>- sólo para altas</small>
                    </h2>
                    <div class="callout primary llamada">
                        <ol>
                            <li><a href="<?php echo INIT ?>/cap/test/errores">Test de ERRORES</a></li>
                            <li><a href="<?php echo INIT ?>/cap/test/resultados">EVOLUCIÓN del AVANCE de resultados</a>
                            </li>

                            <li><a data-open="buscar">LOCALIZACIÓN de Preguntas</a></li>
                            <div class="reveal" data-reveal id="buscar" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Búsqueda</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/buscar">
                                        <label>Tipo búsqueda
                                            <select name="tipo" id="tipoBusqueda">
                                                <option value="pregunta">Pregunta</option>
                                                <option value="codigo">Código</option>
                                            </select>
                                        </label>
                                        <label>¿ Qué busca ?
                                            <input type="text" class="buscarCS" name="buscar" required>
                                        </label>
                                        <p class="help-text">Se permiten números y letras.
                                            Limitado a máximo 100 registros.
                                        </p>
                                        <input type="submit" id="beginBuscar" class="button" value="Comenzar Búsqueda">
                                        <p style="color: red" class="help-text buscar"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a data-open="especifico">Test ESPECÍFICO por palabra clave</a></li>
                            <div class="reveal" data-reveal id="especifico" data-animation-in="spin-in"
                                 data-animation-out="spin-out">
                                <p class="h4">Test Específico</p>
                                <div class="callout success">
                                    <form action="<?php echo INIT ?>/cap/test/especifico">
                                        <label>Tipo
                                            <select name="tipo" id="tipoEspecifico">
                                                <option value="mercancia">Mercancia</option>
                                                <option value="viajeros">Viajeros</option>
                                            </select>
                                        </label>
                                        <label>Palabra clave
                                            <input type="text" name="clave" id="clave" pattern="^([0-9]*[a-z]*[A-Z]*)+$"
                                                   required>
                                        </label>
                                        <p class="help-text" id="passwordHelpText">
                                            La palabra clave estará compuesta por números y letras y no podrá contener
                                            espacios ni tilde.
                                        </p>
                                        <label>Número Preguntas
                                            <input type="text" name="preguntas" id="preguntas"
                                                   pattern="^(10|[1-9][0-9]|100)$" required>
                                        </label>
                                        <p class="help-text">El máximo será 100, y el mínimo 10</p>
                                        <input type="submit" id="beginEspecifico" class="button"
                                               value="Comenzar Examen">
                                        <p style="color: red" class="help-text E"></p>
                                    </form>
                                </div>
                                <button class="close-button" data-close aria-label="Close modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <li><a href="<?php echo INIT ?>/cap/test/examenes-reales">Simulacros de EXAMENES reales</a>
                            </li>
                        </ol>
                    </div>
                </div>
                <div class="medium-6 cell radius">
                    <h4 class="tarjeta text-center" title="Siga el enlace para más información">ESPECIAL PROFESORES
                        <small>- sólo para altas</small>
                    </h4>
                    <div class="callout primary llamada text-center">
                        <a href="<?php echo INIT ?>/cap/test/admin-profe" title="Siga el enlace para más información">Pon
                            a prueba a tus alumnos</a><span style="color: #c7254e;">    (Nuevo)</span>
                    </div>
                    <h5 class="tarjeta text-center">SE AGRADECIDO Y COMPARTE</h5>
                    <div class="callout primary llamada text-center">
                        <!--
                        <div class="fb-like" data-href="http://www.mundocap.es" data-layout="button" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div>

                        <hr>
                        -->
                        <p><em style="color: #3a6291">Este sitio conlleva un gasto y esfuerzo. Por favor se agradecido
                                con ello y comparte.</em></p>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=www.mundocap.es"><i
                                    class="fi-social-facebook" style="font-size: 1.4em;"></i> Compartir en Facebook</a>
                        <br>
                        <a href="https://twitter.com/home?status=www.mundocap.es"><i class="fi-social-twitter"
                                                                                     style="font-size: 1.4em;"></i>Compartir
                            en Twitter</a>
                        <br>
                        <!--
                        <video width="100%" height="100%" controls preload="none">
                            <source src="<?php echo INIT ?>/src/video/mundoCAP.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
                            <source src="<?php echo INIT ?>/src/video/mundoCAP.webm" type='video/webm; codecs="vp8, vorbis"' />
                            <source src="<?php echo INIT ?>/src/video/mundoCAP.ogv" type='video/ogg; codecs="theora, vorbis"' />
                            Este video no es soportado por su navegador. Baje el plugging o visualícelo en otro navegador.
                        <video>
                        -->
                    </div>
                </div>
            </div>

            <div class="grid-x grid-margin-x grid-padding-x todo6">
                <div class="medium-12 cell radius">
                    <div class="callout primary llamada text-center" style="font-size: 1rem">
                        Si desea una WEB personalizada o aplicación empresarial puede
                        <a href="<?php echo INIT ?>/cap/email">contactar</a>
                        conmigo, y me pondré en contacto con usted lo más pronto posible
                    </div>
                </div>
            </div>

            <div class="grid-x grid-padding-x todo5 align-center">
                <div class="medium-6  cell radius">
                    <h3>INFORMACIÓN SOBRE EL CAP</h3>
                    <hr>
                    <p>
                        El <b>certificado de aptitud profesional (CAP)</b>, acreditativo de la correspondiente
                        cualificación inicial es necesario para la conducción por vías públicas españolas de vehículos
                        para los que resulte obligatorio estar en posesión de permisos de conducción de las categorías
                        C1, C1+E, C, C+E, D1, D1+E, D o D+E.
                    </p>
                    <p>
                        Para su obtención se requiere superar un examen, antes de 6 meses, después de realizar un curso
                        de formación.
                    </p>
                    <p>
                        El examen consta de <b>100 preguntas de test</b> (25 para la ampliación de la actividad de
                        viajeros a mercancías y viceversa). Las respuestas correctas valen 1 punto, las erróneas se
                        penalizan con -0,5, las no contestadas no puntúan. Para aprobar es necesario al menos 50 puntos.
                    </p>
                    <p>
                        Las pruebas para obtener el certificado de aptitud profesional se regulan en el <b>Real Decreto
                            1032/2007</b>, de 20 de julio (BOE de 2 de agosto de 2007), en cuyo Anexo I, figura el
                        programa de las materias de los cursos de cualificación sobre cuyo contenido versará el examen.
                    </p>
                    <p>
                        Los exámenes son convocados y realizados, al menos 6 veces al año, por las Comunidades Autónomas
                        competentes.
                    </p>
                    <p>
                        Los aspirantes podrán realizar los cursos de formación en cualquier parte del territorio
                        nacional pero deberán concurrir a las pruebas que se convoquen y realicen por los órganos
                        competentes en aquel territorio en el que tengan su residencia habitual.
                    </p>
                </div>
                <div class="medium-4 cell radius" style="font-size: 1.1rem">
                    <h4 class="h3">SOBRE ESTA WEB</h4>
                    <br>
                    <p>Está en constante renovación y desarrollo para que la información
                        aquí encontrada le sea de utilidad.</p>
                    <p>Se pretende la rápidez en la enseñanza y no el tiempo de permanencia
                        en la WEB; de ahí, que se obtenga todas las preguntas del examen solicitado
                        de una vez; y no, de una en una como es habitual ver en otros sitios.</p>
                    <p>Si conoce algún error u omisión ruego se ponga en contacto conmigo para que
                        pueda corregirlo.</p>
                    <p>Cualquier sugerencia o duda será bienvenida y respondida lo antes posible.</p>
                </div>
            </div>

        </div>


        <?php require_once 'footer.phtml' ?>

    </div>
</div>

<?php if (empty($_SESSION['ocultarC'])) {
    require_once 'ocultar.phtml';
} ?>

<script defer src="<?php echo INIT ?>/modules/jquery/dist/jquery.js"></script>
<script defer src="<?php echo INIT ?>/modules/what-input/dist/what-input.js"></script>
<script defer src="<?php echo INIT ?>/modules/foundation-sites/dist/js/foundation.js"></script>
<script defer src="<?php echo INIT ?>/src/js/app1.js"></script>

<?php if (MODO == 'production') { ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-50863084-1', 'mundocap.es');
        ga('send', 'pageview');
    </script>
<?php } ?>

</body>
</html>