<!doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="mundocap, cap, login, acceso, inicio sesion" />
    <meta name="author" content="Fco Sanz">
    <meta name="description" content="Permite loguearse en mundoCAP">
    <title>Login MundoCap</title>
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/test.css">
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/foundation-icons.css">
</head>
<body>
<noscript>
    <p>Su navegador no admite javascript. Por favor activeló para la navegación.</p>
</noscript>
<header id="foo">
    <div class="grid-x navegacion grid-padding-x">
        <div class="cell">
            <div class="top-bar">
                <div class="top-bar-left">
                    <a href="<?php echo INIT?>/">
                        <img src="<?php echo INIT?>/src/images/globo3.png" height="62" width="62">
                    </a>
                    <h2 style="display: none;">certificado de aptitud Profesional</h2>
                </div>
                <div class="top-bar-right">
                    <a data-toggle="menuPrincipal" class="menu-icon" style="line-height: -10rem;"></a>
                </div>
            </div>
        </div>
    </div>
</header>
<br>
<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
        <nav class="off-canvas position-left" id="menuPrincipal" data-off-canvas data-transition="push">
            <?php require_once 'navegacion.phtml'?>
        </nav>

        <div class="off-canvas-content" data-off-canvas-content>
            <div class="grid-x grid-padding-x grid-padding-y">
                <div class="cell small-1 medium-3 large-4"></div>
                <div class="cell small-10 medium-6 large-4" style="border: 2px solid #00A5E3">
                    <h4 class="text-center"><i style="color: #2ca02c">Acceso a MundoCAP</i></h4>
                    <br>
                    <form action="<?php echo INIT?>/cap/login" method="post">
                        <input type="hidden" name="skey" value="<?php echo $skey?>">
                        <input type="text" name="email" required placeholder="E-MAIL">
                        <input type="password" name="contrasena" required placeholder="CONTRASEÑA">
                        <input type="submit" class="success expanded button" value="Entrar">
                    </form>

                    <p class="h6 text-center">¿Ha olvidado usted sus datos?
                        <br><a href="<?php echo INIT?>/cap/recuperar"><strong style="color: #3a6291;">Recuperar</strong></a>
                    </p>
                    <p class="text-center">¿No tienes cuenta aún?</p>
                    <a href="<?php echo INIT?>/cap/alta" class="button expanded">Crear Cuenta</a>
                    <p class="h6 help-text" style="color: red">
                        <?php if (isset($info)) echo $info?>
                    </p>
                </div>
                <div class="cell small-1 medium-3 large-4"></div>
            </div>
            <div class="grid-x grid-padding-x grid-padding-y">
                <div class="cell small-1 medium-3 large-4"></div>
                <div class="cell small-10 medium-6 large-4">
                    <hr>
                    <p><a href="<?php echo INIT?>/cap/cookies">Privacidad</a> <span style="color: #3a6291;">|</span> <a href="<?php echo INIT?>/cap/baja">Baja</a></p>
                </div>
                <div class="cell small-1 medium-3 large-4"></div>
            </div>
        </div>
    </div>
</div>

<?php if (empty($_SESSION['ocultarC'])) {
    require_once 'ocultar.phtml';
}?>

<script src="<?php echo INIT?>/modules/jquery/dist/jquery.js"></script>
<script src="<?php echo INIT?>/modules/what-input/dist/what-input.js"></script>
<script src="<?php echo INIT?>/modules/foundation-sites/dist/js/foundation.js"></script>
<script src="<?php echo INIT?>/src/js/app2.js"></script>

<?php if (MODO=='production'){ ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50863084-1', 'mundocap.es');
        ga('send', 'pageview');

    </script>
<?php } ?>
</body>
</html>