<br>
<ul class="menu vertical">
    <li style="text-decoration: underline; color: #32547d; margin-left: 1rem;">MENÚ</li>
    <li><a href="https://www.facebook.com/sharer/sharer.php?u=www.mundocap.es" aria-label="compartir en Facebook"><i class="fi-social-facebook" style="font-size: 1.4em;"></i> Comparte</a></li>
    <li><a href="https://twitter.com/home?status=www.mundocap.es" aria-label="compartir en Twitter"><i class="fi-social-twitter" style="font-size: 1.4em;"></i>Comparte</a></li>
    <li><a href="<?php echo INIT?>/cap/login">Inicio Sesión</a></li>
    <li><a href="<?php echo INIT?>/cap/alta">Dese de Alta</a></li>
    <li><a href="<?php echo INIT?>/cap/logout">Cierre Sesión</a></li>
    <li><a href="<?php echo INIT?>/cap/baja">Baja</a></li>
    <li><a href="<?php echo INIT?>/cap/cookies">Cookies/Uso/Condiciones</a></li>
    <li><a href="<?php echo INIT?>/cap/email">Contacta Conmigo</a></li>
</ul>