<div class="callout ocultar" style="position: fixed; bottom: 0; width: 100%; height: auto; margin-bottom: 0; z-index: 11111111; ">
    <div class="grid-x">
        <div class="cell medium-10">
            <p>En esta WEB, obvio, se utilizan cookies para ofrecer una mejor experiencia al usuario y serle útil.
                Al navegar por ella usted acepta este uso.</p>
            <p>Si desea una información más exhaustiva puede informarse en
                <a href="<?php echo INIT?>/cookies">Política de Cookies y uso</a></p>
        </div>
        <div class="cell medium-2" style="border-left: 2px dotted #4472a9;">
            <div class="text-center">
                <br>
                <button id="ojo" onclick="remover()" style="cursor: pointer; background-color: #4472a9; color: white" type="button" class="success button remove" data-order="<?php echo INIT?>/remover" aria-label="Dismiss alert">Aceptar</button>
            </div>
        </div>
    </div>
</div>