<!doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type: text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="es" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="cap, resultados cap, errores examentes cap, examenes cap, examenes mercancia, examenes viajeros, test viajeros, test mercancias" />
    <meta name="author" content="Fco Sanz">
    <meta name="description" content="Permite ver los resultados de los test realizados hasta ahora">
    <title>Resultado MundoCap</title>

    <link rel="stylesheet" href="<?php echo INIT?>/src/css/test.css">
    <link rel="stylesheet" href="<?php echo INIT?>/src/css/foundation-icons.css">
</head>
<body>

<noscript>
    <p>Su navegador no admite javascript. Por favor activeló para la navegación.</p>
</noscript>

<a name="arriba"></a>

<form name="myForm" id="inicio" action="<?php echo INIT?>/cap/test/grabar-errores" method="post">
    <header id="foo">
        <div class="grid-x navegacion grid-padding-x">
            <div class="cell">
                <div class="top-bar">
                    <div class="top-bar-left">
                        <a href="<?php echo INIT?>/">
                            <img src="<?php echo INIT?>/src/images/globo3.png" height="62" width="62">
                        </a>
                        <h2 style="display: none;">certificado de aptitud Profesional</h2>
                    </div>
                    <div class="top-bar-right">
                        <a data-toggle="menuPrincipal" class="menu-icon" style="line-height: -10rem;"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid-x grid-padding-x">
            <div class="cell">
                <a href="<?php echo INIT?>/">Inicio</a>  >> <span style="color: #2ca02c"><?php echo $enlace?></span>
            </div>
        </div>

        <div class="grid-x">
            <div class="cell">
                <div class="callout primary">
                    <p>
                        Aquí encontrará sus resultados. Podrá analizar su avance en el tiempo.
                        La nota está en porcentajes ( sobre 100 ).
                    </p>
                    <p>
                        <i><strong>Versión Actualizada a 20/08/2018</strong></i>
                    </p>
                </div>
            </div>
        </div>
    </header>

    <div class="off-canvas-wrapper">
        <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
            <nav class="off-canvas position-left" id="menuPrincipal" data-off-canvas data-transition="push">
                <?php require_once 'navegacion.phtml'?>
            </nav>

            <div class="off-canvas-content" data-off-canvas-content>
                <section class="grid-container">
                    <div class="table-scroll">
                    <table class="hover">
                        <thead>
                        <tr>
                            <th width="200">Fecha</th>
                            <th>Nota</th>
                            <th width="150">Aciertos</th>
                            <th width="150">Fallos</th>
                            <th width="150">Nulas</th>
                            <th width="150">Tiempo (min.)</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($resultados as $resultado) { ?>
                            <tr>
                                <td><?php echo date("j/m/Y", strtotime($resultado->fecha))?></td>
                                <td><?php echo $resultado->nota?></td>
                                <td><?php echo $resultado->acierto?></td>
                                <td><?php echo $resultado->fallo?></td>
                                <td><?php echo $resultado->nula?></td>
                                <td><?php echo $resultado->reloj?></td>
                            </tr>
                            <?php }?>
                        </tbody>
                    </table>
                    </div>
                    <?php if (empty($resultados)) echo 'Lo sentimos. No tiene aún ningún test grabado'?>
                </section>
            </div>
</form>
<br>
<?php require_once 'footer.phtml'?>
</div>
</div>

<?php if (empty($_SESSION['ocultarC'])) {
    require_once 'ocultar.phtml';
}?>

<script src="<?php echo INIT?>/modules/jquery/dist/jquery.js"></script>
<script src="<?php echo INIT?>/modules/what-input/dist/what-input.js"></script>
<script src="<?php echo INIT?>/modules/foundation-sites/dist/js/foundation.js"></script>
<script src="<?php echo INIT?>/src/js/app.js"></script>

<?php if (MODO=='production'){ ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50863084-1', 'mundocap.es');
        ga('send', 'pageview');

    </script>
<?php } ?>
</body>